import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { scanRepo, detectStack, gradeOf } from '../src/scan.js';
import { renderHTML, renderPortfolioHTML } from '../src/render-html.js';
import { renderClaude } from '../src/render-claude.js';
import { renderTerminal } from '../src/render-terminal.js';

function makeRepo(files) {
  const dir = mkdtempSync(join(tmpdir(), 'reporadar-'));
  for (const [rel, content] of Object.entries(files)) {
    const full = join(dir, rel);
    mkdirSync(join(full, '..'), { recursive: true });
    writeFileSync(full, content);
  }
  return dir;
}

test('detectStack recognizes Node + TypeScript', () => {
  const dir = makeRepo({ 'package.json': '{}', 'tsconfig.json': '{}' });
  const stack = detectStack(dir);
  assert.ok(stack.includes('Node/JS'));
  assert.ok(stack.includes('TypeScript'));
  rmSync(dir, { recursive: true, force: true });
});

test('gradeOf maps scores to letter grades', () => {
  assert.equal(gradeOf(95), 'A');
  assert.equal(gradeOf(72), 'B');
  assert.equal(gradeOf(30), 'F');
});

test('scanRepo flags a hardcoded secret as red security', () => {
  const dir = makeRepo({
    'package.json': '{"name":"x","scripts":{"start":"node i.js"}}',
    'src/app.js': 'const k = "sk-ant-' + 'A'.repeat(30) + '";',
  });
  const result = scanRepo(dir);
  const sec = result.dimensions.find((d) => d.key === 'secrets');
  assert.equal(sec.status, 'red');
  assert.ok(sec.fixes.some((f) => /P0/.test(f)), 'should produce a P0 fix');
  rmSync(dir, { recursive: true, force: true });
});

test('.reporadarignore excludes a fixture path from the secret scan', () => {
  const dir = makeRepo({
    'package.json': '{"name":"x"}',
    'fixtures/leak.js': 'const k = "sk-ant-' + 'A'.repeat(30) + '";',
    '.reporadarignore': '# fixtures carry synthetic secrets\nfixtures/\n',
  });
  const result = scanRepo(dir);
  const sec = result.dimensions.find((d) => d.key === 'secrets');
  assert.equal(sec.status, 'green', 'an ignored fixture secret must not count against the grade');
  rmSync(dir, { recursive: true, force: true });
});

test('without .reporadarignore the same fixture secret is still flagged (detection intact)', () => {
  const dir = makeRepo({
    'package.json': '{"name":"x"}',
    'fixtures/leak.js': 'const k = "sk-ant-' + 'A'.repeat(30) + '";',
  });
  const result = scanRepo(dir);
  const sec = result.dimensions.find((d) => d.key === 'secrets');
  assert.equal(sec.status, 'red', 'a secret in a non-ignored path must still be caught');
  rmSync(dir, { recursive: true, force: true });
});

test('scanRepo rewards a well-formed repo', () => {
  const longReadme = '# Project\n\n' + '## Install\nrun it.\n## Usage\n' + 'x'.repeat(1600);
  const dir = makeRepo({
    'package.json': '{"name":"good","scripts":{"test":"node --test","build":"tsc"},"dependencies":{"express":"^4.0.0"}}',
    'package-lock.json': '{}',
    'README.md': longReadme,
    'LICENSE': 'MIT',
    '.gitignore': 'node_modules\n.env\n',
    '.eslintrc.json': '{}',
    'test/app.test.js': 'import {test} from "node:test"; test("x",()=>{});',
    '.github/workflows/ci.yml': 'jobs:\n  test:\n    steps:\n      - run: node --test\n',
  });
  const result = scanRepo(dir);
  assert.ok(result.overall >= 70, `expected healthy score, got ${result.overall}`);
  const sec = result.dimensions.find((d) => d.key === 'secrets');
  assert.equal(sec.status, 'green');
  rmSync(dir, { recursive: true, force: true });
});

test('renderers produce non-empty output without throwing', () => {
  const dir = makeRepo({ 'package.json': '{"name":"r"}', 'README.md': '# hi' });
  const result = scanRepo(dir);
  const html = renderHTML(result);
  assert.ok(html.includes('<!doctype html>'));
  assert.ok(html.includes('RepoRadar'));
  assert.ok(renderClaude(result).includes('Fix Plan'));
  assert.ok(renderTerminal(result).includes('Overall'));
  assert.ok(renderPortfolioHTML([result, result]).includes('portfolio'));
  rmSync(dir, { recursive: true, force: true });
});

test('renderHTML white-labels the report with a brand (Team tier)', () => {
  const dir = makeRepo({ 'package.json': '{"name":"acme"}', 'README.md': '# acme' });
  const result = scanRepo(dir);
  const branded = renderHTML(result, { brand: 'Northwind Audits' });
  assert.ok(branded.includes('Northwind Audits'), 'brand name appears in the report');
  assert.ok(branded.includes('Generated by Northwind Audits'), 'footer is white-labeled');
  assert.ok(!/>RepoRadar<\/h1>/.test(branded), 'default RepoRadar header is replaced when branded');
  assert.ok(renderHTML(result).includes('RepoRadar'), 'unbranded report still shows RepoRadar');
  rmSync(dir, { recursive: true, force: true });
});

test('overall score is a weighted 0-100 integer', () => {
  const dir = makeRepo({ 'package.json': '{"name":"z"}' });
  const result = scanRepo(dir);
  assert.ok(Number.isInteger(result.overall));
  assert.ok(result.overall >= 0 && result.overall <= 100);
  assert.ok(['green', 'yellow', 'red'].includes(result.status));
  rmSync(dir, { recursive: true, force: true });
});
