// Renders a Claude Code-ready fix plan from a scan result.
// This is RepoRadar's differentiator: scan -> score -> paste this into Claude Code -> fixes.

export function renderClaude(result) {
  const reds = result.dimensions.filter((d) => d.status === 'red');
  const yellows = result.dimensions.filter((d) => d.status === 'yellow');
  const allFixes = result.dimensions.flatMap((d) => d.fixes.map((f) => ({ dim: d.label, status: d.status, fix: f })));
  // P0 = secrets/security fixes, then reds, then yellows.
  const rank = (x) => (/\(P0\)/.test(x.fix) ? 0 : x.status === 'red' ? 1 : x.status === 'yellow' ? 2 : 3);
  const ordered = [...allFixes].sort((a, b) => rank(a) - rank(b));

  const lines = [];
  lines.push(`# RepoRadar Fix Plan — ${result.name}`);
  lines.push('');
  lines.push(`> Generated by RepoRadar. Paste this into Claude Code and say: "Work through this fix plan top to bottom, committing at each clean checkpoint."`);
  lines.push('');
  lines.push(`**Health: ${result.grade} (${result.overall}/100)** · Stack: ${result.stack.join(', ')}`);
  lines.push('');
  lines.push(`- 🔴 ${reds.length} red dimension(s): ${reds.map((d) => d.label).join(', ') || 'none'}`);
  lines.push(`- 🟡 ${yellows.length} yellow dimension(s): ${yellows.map((d) => d.label).join(', ') || 'none'}`);
  lines.push('');
  lines.push('## Prioritized fixes');
  lines.push('');
  if (!ordered.length) {
    lines.push('No fixes required — this repo is in good shape. 🎉');
  } else {
    ordered.forEach((x, i) => {
      const p = /\(P0\)/.test(x.fix) ? '🚨 ' : '';
      lines.push(`${i + 1}. ${p}**[${x.dim}]** ${x.fix}`);
    });
  }
  lines.push('');
  lines.push('## Guardrails for the fixing agent');
  lines.push('');
  lines.push('- Make minimal, reviewable diffs; commit at each clean checkpoint.');
  lines.push('- Never commit or print secrets — for any P0 secret finding, document the type and location only and recommend rotation.');
  lines.push('- Run the test suite after each change; do not claim done-and-verified without running it.');
  lines.push('- Re-run `reporadar scan .` at the end to confirm the grade improved.');
  lines.push('');
  return lines.join('\n');
}
